name: rexofarm
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  dotted_border: ^2.0.0+3
  font_awesome_flutter: ^10.4.0
  image_picker: ^0.8.7+5
  google_fonts: ^4.0.4
  http: ^0.13.6
  phone_number: ^2.0.1
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  percent_indicator: ^4.2.3
  auto_size_text: ^3.0.0
  intl: ^0.18.1
  shimmer: ^3.0.0
  path: ^1.8.3
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/
    - images/onboarding/
    - images/assets/
    - images/profile/

  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf
        - asset: fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: fonts/Quicksand-Light.ttf
          weight: 300





  
